//
//  SecondViewController.swift
//  MVPModule
//
//  Created tambanco 🥳 on 13.03.2022.
//
//  Template generated by Tambanco
//

import UIKit

class SecondViewController: UIViewController {

	var presenter: SecondPresenterProtocol!

	override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}

// MARK: - Binding
extension SecondViewController: SecondViewProtocol {
    
}
