//
//  SecondPresenter.swift
//  MVPModule
//
//  Created tambanco 🥳 on 13.03.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol SecondViewProtocol: AnyObject {

}

// MARK: Input protocol
protocol SecondPresenterProtocol: AnyObject {
    init(view: SecondViewProtocol, model:  SecondModel)

}

class SecondPresenter: SecondPresenterProtocol {

    weak var view: SecondViewProtocol?
    var model: SecondModel
    
    // Enter buisness logic here
    
    required init(view: SecondViewProtocol, model: SecondModel) {
        self.view = view
        self.model = model
    }
}
